# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 180
    Tracing: Active

Resources:
  StockAgg:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.default
      CodeUri: ./dist/index
